# Машинное обучение. Практическая работа

В этой практической работе четыре обязательные задачи.

Они помогут понять, что вы действительно усвоили материал модуля. 


Удачи!

## Цели практической работы

Научиться:
- обучать модели, основанные на деревьях решений;
- научиться оценивать и увеличивать их качество.

## Что входит в практическую работу

1. Загрузите датасет и ознакомьтесь с ним.
2. Подготовьте базовую модель дерева решений и измерьте её качество.
3. Подготовьте базовую модель случайного леса и измерьте её качество.
4. Увеличьте точность модели случайного леса на тестовых данных.
5. Проведите анализ влияния признаков на модель.

## Что оценивается

* Выполнены все четыре задачи. Для каждой:
 * в коде нет ручных перечислений, все действия автоматизированы;
 * результаты вычислений и применённых операций корректны;
 * ответы на вопросы, где требуется, корректны и обоснованы; 
 * код читабелен: переменным даны осмысленные названия, соблюдены отступы и правила расстановки пробелов; стилизация кода соответствует рекомендациям [PEP 8](https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html).

* Репозиторий проекта оформлен корректно:
 * содержит осмысленные коммиты, содержащие конкретные реализованные фичи;
 * ветки названы согласно назначению;
 * файлы, не связанные с проектом, не хранятся в репозитории.


## Как отправить работу на проверку

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

## Обязательные задачи

### Описание датасета:
- `id`— идентификатор записи;
- `is_manufacturer_name`— признак производителя автомобиля;

- `region_*`— регион;
- `x0_*`— тип топлива;
- `manufacturer_*`— производитель;
- `short_model_*`— сокращённая модель автомобиля;
- `title_status_*`— статус;
- `transmission_*`— коробка передач;
- `state_*`— штат;
- `age_category_*`— возрастная категория автомобиля;

- `std_scaled_odometer`— количество пройденных миль (после стандартизации);
- `year_std`— год выпуска (после стандартизации);
- `lat_std`— широта (после стандартизации);
- `long_std`— долгота (после стандартизации);
- `odometer/price_std`— отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`— количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`— количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`— длина наименования автомобиля (после стандартизации);
- `model_word_count_std`— количество слов в наименовании автомобиля (после стандартизации);
- `month_std`— номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`— день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`— количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`— стоимость;
- `price_category`— категория цены.

1. Подготовка базовой модели

Обучите простую модель классификации с помощью DecisionTreeClassifier на данных из датасета vehicles_dataset_prepared.csv. Для этого сделайте шаги:

1. Обучите модель дерева решений с зафиксированным random_state на тренировочной выборке.
2. Сделайте предикт на тестовой выборке.
3. Замерьте точность на тестовой выборке и выведите матрицу ошибок. 
4. Удалите фичи с нулевыми весами по feature_importance из тренировочной и тестовой выборок.
5. Заново обучите модель и измерьте качество.

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix 

In [4]:
df = pd.read_csv('data/vehicles_dataset_prepared.csv')

df_prepared = df.copy()
df_prepared = df_prepared.drop(['price', 'odometer/price_std'], axis=1)

x = df_prepared.drop(['price_category'], axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

In [85]:
clf = DecisionTreeClassifier() 
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [6]:
predicted_train = clf.predict(x_train) 
predicted_test = clf.predict(x_test)

In [7]:
print(accuracy_score(y_train, predicted_train))
print(accuracy_score(y_test, predicted_test))

1.0
0.6715176715176715


In [9]:
confusion_matrix(y_train, predicted_train)

array([[2202,    0,    0],
       [   0, 2247,    0],
       [   0,    0, 2284]], dtype=int64)

In [10]:
confusion_matrix(y_test, predicted_test)

array([[733,  54, 210],
       [ 47, 682, 224],
       [184, 229, 523]], dtype=int64)

In [8]:
clf.feature_importances_

array([0.03145068, 0.00080186, 0.00371078, ..., 0.0013134 , 0.0164396 ,
       0.04093891])

In [33]:
f_imp_list = list(zip(x_train.columns, clf.feature_importances_))
f_imp_list.sort(key=lambda x: x[1], reverse=True)
f_imp_list

[('year_std', 0.20060156885416314),
 ('std_scaled_odometer', 0.07889169462137575),
 ('model_len_std', 0.07682518675883372),
 ('desc_len_std', 0.06925546986810276),
 ('lat_std', 0.040960072705816294),
 ('diff_years_std', 0.04093891110682052),
 ('long_std', 0.03868318773374364),
 ('x0_diesel', 0.03381094759490495),
 ('id', 0.03145067817358126),
 ('dayofweek_std', 0.016439600885753827),
 ('short_model_wrangler', 0.009446703472159208),
 ('manufacturer_kia', 0.009142192303278453),
 ('manufacturer_ram', 0.008715580410053736),
 ('short_model_f-150', 0.006887403899017633),
 ('manufacturer_hyundai', 0.005997972193863719),
 ('model_word_count_std', 0.005714827279202875),
 ('manufacturer_chevrolet', 0.005218598334050709),
 ('short_model_silverado', 0.005153074650174036),
 ('manufacturer_gmc', 0.005071322654192766),
 ('short_model_Scion', 0.004865746378858323),
 ('model_in_desc_std', 0.004637087199617459),
 ('manufacturer_mercedes-benz', 0.004614266590743074),
 ('short_model_tacoma', 0.00414389798

In [40]:
columns_to_remove = [feature for feature, value in f_imp_list if value == 0]
columns_to_remove

['short_model_-benz',
 'short_model_1',
 'short_model_124',
 'short_model_128i',
 'short_model_135i',
 'short_model_163869',
 'short_model_1928',
 'short_model_1951',
 'short_model_1954',
 'short_model_1960s',
 'short_model_1966',
 'short_model_1972',
 'short_model_1977',
 'short_model_1978',
 'short_model_198.5',
 'short_model_1988',
 'short_model_1994',
 'short_model_1999',
 'short_model_2',
 'short_model_200',
 'short_model_2000',
 'short_model_2002',
 'short_model_2006',
 'short_model_2007',
 'short_model_2008',
 'short_model_2009',
 'short_model_2012',
 'short_model_2015',
 'short_model_2016',
 'short_model_2017',
 'short_model_2018',
 'short_model_210',
 'short_model_240',
 'short_model_2500hd',
 'short_model_280zx',
 'short_model_3',
 'short_model_3-series',
 'short_model_3-window',
 'short_model_3.2',
 'short_model_300',
 'short_model_300-series',
 'short_model_300c',
 'short_model_300s',
 'short_model_300zx',
 'short_model_3100',
 'short_model_318i',
 'short_model_320i',
 'sho

In [42]:
df_removed = df_prepared.drop(columns=columns_to_remove)

x = df_removed.drop(['price_category'], axis=1)
y = df_removed['price_category']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

In [43]:
clf = DecisionTreeClassifier() 
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [44]:
predicted_train = clf.predict(x_train) 
predicted_test = clf.predict(x_test)

In [45]:
print(accuracy_score(y_train, predicted_train))
print(accuracy_score(y_test, predicted_test))

1.0
0.6781011781011781


2. Подготовка модели случайного леса

Обучите простую модель классификации с помощью RandomForestClassifier. Для этого на новых урезанных семплах тренировочной и тестовой выборок обучите модель случайного леса с зафиксированным random_state=50. 

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=50)

In [53]:
rt_clf = RandomForestClassifier()
rt_clf.fit(x_train, y_train)

RandomForestClassifier()

2. Сделайте предикт, посчитайте точность модели и матрицу ошибок. Сравните с предыдущей моделью дерева решений. Есть ли случаи, когда модель из пункта 1 отрабатывает лучше, чем модель случайного леса?

In [57]:
predicted_train_rf = rt_clf.predict(x_train)
predicted_test_rf = rt_clf.predict(x_test)

In [58]:
print(accuracy_score(y_train, predicted_train_rf))
print(accuracy_score(y_test, predicted_test_rf))

1.0
0.764033264033264


In [59]:
confusion_matrix(y_train, predicted_train)

array([[774, 743, 736],
       [709, 759, 757],
       [719, 745, 791]], dtype=int64)

In [60]:
confusion_matrix(y_test, predicted_test)

array([[299, 332, 315],
       [340, 346, 289],
       [337, 300, 328]], dtype=int64)

3. Тюнинг модели случайного леса

Увеличьте точность модели на тестовом датасете RandomForestClassifier c помощью тюнинга параметров. 

Параметры, которые можно настраивать для увеличения точности:
```
    `bootstrap'
    'max_depth'
    'max_features'
    'min_samples_leaf'
    'min_samples_split'
    'random_state'
    'n_estimators'

```

С описанием каждого из параметров можно ознакомиться [в документации](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html).

Задание засчитывается, если значение метрики строго выше 0.76 на тестовом датасете.

In [64]:
param_grid = {
    'bootstrap': [True, False],
    'max_depth': [None, 10, 20],
    'max_features': ['auto', 'sqrt', 'log2'],
    'min_samples_leaf': [1, 2, 4],
    'min_samples_split': [2, 5, 10],
    'random_state': [42], 
    'n_estimators': [50, 100, 200]
}



In [65]:
from sklearn.model_selection import GridSearchCV

In [73]:
rf = RandomForestClassifier(random_state=42)

# Модель для перебора параметров базовой модели
grid_search_rf = GridSearchCV(
   estimator=rf,
   param_grid=param_grid,
   scoring='accuracy',
   verbose=1,
   n_jobs=-1
)

In [74]:
grid_search_rf.fit(x_train, y_train)

best_params = grid_search_rf.best_params_
best_params

Fitting 5 folds for each of 486 candidates, totalling 2430 fits


C:\Users\tatev\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
810 fits failed out of a total of 2430.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
321 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\tatev\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\tatev\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\tatev\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\tatev\anaconda3\Lib\site-packa

{'bootstrap': False,
 'max_depth': None,
 'max_features': 'log2',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 200,
 'random_state': 42}

In [75]:
rf_tuned = RandomForestClassifier(bootstrap=False, max_depth = None, max_features = 'log2',min_samples_leaf=1,min_samples_split = 2,
 n_estimators = 200, random_state = 42)
rf_tuned.fit(x_train, y_train)

preds = rf_tuned.predict(x_test)
accuracy_score(y_test, preds)
print(f'Tuned RF Model Accuracy: {accuracy_score(y_test, preds):.5f}')

Tuned RF Model Accuracy: 0.77304


4. Анализ влияния фичей на модель

До этого в задачах вы работали над подготовленным датасетом, где фичи были заранее извлечены из текстовых переменных, отскейлены и пропущены через OneHotEncoder. Сравним, какой была бы предсказательная способность модели, если бы мы использовали только сырые данные из исходного датасета. Для этого проделайте следующие шаги:

1. Загрузите датасет `vehicles_dataset_old.csv`.
2. Удалите из него переменную `price` и все строковые колонки. Дерево решений и случайный лес не умеют самостоятельно работать со строковыми значениями.
3. Сформируйте x_train и x_test так же, как они были сформированы в предыдущих заданиях.
4. Обучите свою лучшую модель случайного леса на новых данных и замерьте качество. Убедитесь, что оно ухудшилось.
5. Найдите три фичи, которые лучшим образом повлияли на предсказательную способность модели.

In [81]:
df_old = pd.read_csv('data/vehicles_dataset_old.csv')
df_old.head(5)

id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...   
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...   
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...   
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...   
4  7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...   

         region                           region_url  price  year  \
0   chattanooga   https://chattanooga.craigslist.org  54990  2020   
1  north jersey     https://newjersey.craigslist.org  16942  2016   
2  reno / tahoe          https://reno.craigslist.org  35590  2017   
3  fayetteville  https://fayetteville.craigslist.org  14500  2013   
4     knoxville     https://knoxville.craigslist.org  14590  2012   

  manufacturer                   model    fuel  odometer title_status  \
0          ram  2500 crew cab big horn  diesel     27442        clean   
1         ford    explorer 4wd 4dr xlt   other     60023        clean   
2   volkswagen        golf r hatchback     gas     14048        clean   
3       toyota                    rav4     gas    117291        clean   
4          bmw  1 series 128i coupe 2d   other     80465        clean   

  transmission                                          image_url  \
0        other  https://images.craigslist.org/00N0N_1xMPvfxRAI...   
1    automatic  https://images.craigslist.org/00x0x_26jl9F0cnL...   
2        other  https://images.craigslist.org/00y0y_eeZjWeiSfb...   
3    automatic  https://images.craigslist.org/00606_iGe5iXidib...   
4        other  https://images.craigslist.org/00F0F_5UAXmOzC18...   

                                         description state        lat  \
0  Carvana is the safer way to buy a car During t...    tn  35.060000   
1  ***Call Us for more information at: 201-635-14...    nj  40.821805   
2  Carvana is the safer way to buy a car During t...    ca  33.779214   
3  2013 Toyota RAV4 XLE 4dr SUV     Offered by: R...    nc  35.715954   
4  Carvana is the safer way to buy a car During t...    tn  35.970000   

        long              posting_date price_category  \
0 -85.250000  2021-04-17T12:30:50-0400           high   
1 -74.061962  2021-05-03T15:40:21-0400         medium   
2 -84.411811  2021-04-28T03:52:20-0700           high   
3 -78.655304  2021-04-17T10:08:57-0400         medium   
4 -83.940000  2021-04-08T15:10:56-0400         medium   

                        date  
0  2021-04-17 16:30:50+00:00  
1  2021-05-03 19:40:21+00:00  
2  2021-04-28 10:52:20+00:00  
3  2021-04-17 14:08:57+00:00  
4  2021-04-08 19:10:56+00:00

In [80]:
df_old.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'fuel', 'odometer', 'title_status', 'transmission',
       'image_url', 'description', 'state', 'lat', 'long', 'posting_date',
       'price_category', 'date'],
      dtype='object')

In [88]:
df_old_prepared = df_old.copy()

df_old_prepared = df_old_prepared.drop(['url', 'region', 'region_url', 'price', 'manufacturer','model','fuel', 'title_status', 'transmission','image_url', 'description', 'state',  'posting_date', 'date'], axis=1)

x = df_old_prepared.drop(['price_category'], axis=1)
y = df_old_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)


In [98]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

rf = RandomForestClassifier()


In [99]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [100]:
predicted_train_rf = rf.predict(x_train)
predicted_test_rf = rf.predict(x_test)

In [101]:
print(accuracy_score(y_train, predicted_train_rf))
print(accuracy_score(y_test, predicted_test_rf))

1.0
0.6313236313236313


In [112]:
import numpy as np
feature_importance_rf = rf.feature_importances_
type(feature_importance_rf)
sorted_arr_axis = np.sort(feature_importance_rf)
sorted_arr_axis[:3]

array([0.16434904, 0.16643001, 0.16804495])

In [124]:
print("Feature Importance for Random Forest:")
feature_imp_d = {}
for feature, importance in zip(x.columns,feature_importance_rf):
    feature_imp_d[feature] = importance
print(feature_imp_d)

Feature Importance for Random Forest:
{'id': 0.16804494854237073, 'year': 0.22188633804642355, 'odometer': 0.2792896618598819, 'lat': 0.16434904354866242, 'long': 0.16643000800266136}


In [125]:
sorted_dict = dict(sorted(feature_imp_d.items(), key=lambda item: item[1]))
feature_three_imp_d = dict(list(sorted_dict.items())[:3])
feature_three_imp_d

{'lat': 0.16434904354866242,
 'long': 0.16643000800266136,
 'id': 0.16804494854237073}